providers:
  ecs:
    clusters:
      - beddybytes-backend-compute-cluster
    exposedByDefault: false

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

certificatesResolvers:
  letsencrypt:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: ryan.a.ballinger@gmail.com
      storage: /etc/traefik/letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: WARN

accessLog:
  filePath: /opt/logs/access.log
  bufferingSize: 128

ping: {}

metrics:
  influxDB2:
    address: http://influxdb:8086
    token: ${INFLUXDB_TOKEN}
    org: beddybytes
    bucket: traefik