AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  InstanceType:
    Type: String
    Description: EC2 instance type for the API server
  PublicKeyMaterial:
    Type: String
    Description: Public key material for the EC2 key pair
  HostedZoneName:
    Description: The name of the hosted zone where the DNS record will be created
    Type: String
  APIDomainName:
    Description: The domain name of the backend API
    Type: String
  InfluxDomainName:
    Description: The domain name of the influxDB
    Type: String
  GrafanaDomainName:
    Description: The domain name of the Grafana
    Type: String
  MyIPAddress:
    Description: The IP address of the client that will be allowed to SSH into the EC2 instance
    Type: String

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      StackName: !Sub ${AWS::StackName}-vpc
  Compute:
    Type: AWS::CloudFormation::Stack
    Properties:
      StackName: !Sub ${AWS::StackName}-compute
      Parameters:
        SubnetID: !GetAtt VPC.Outputs.PublicSubnetID
        InstanceType: !Ref InstanceType
        PublicKeyMaterial: !Ref PublicKeyMaterial
        MyIPAddress: !Ref MyIPAddress
  DNSRecords:
    Type: AWS::CloudFormation::Stack
    Properties:
      StackName: !Sub ${AWS::StackName}-dns
      Parameters:
        PublicIPAddress: !GetAtt Compute.Outputs.PublicIPAddress
        HostedZoneName: !Ref HostedZoneName
        APIDomainName: !Ref APIDomainName
        InfluxDomainName: !Ref InfluxDomainName
        GrafanaDomainName: !Ref GrafanaDomainName
